### PR TITLE
127 fix makerspace components styling

### LINKED ISSUE #127: fix makerspace components styling 🤑
too much text, make it shortened and when you click on it there will be a pop up that allows u to scroll and read
also u forgot the subpages navbar

### PR DESCRIPTION
**Pull request by katiekhamarkhanova**
made it so that articles just display image, headline, and short portion of text (if too much text, it gets cut off by ...)
when user clicks on article, if the article has an external link they are brought to that but if no external link, a popup appears with the full article text (scroll to read) along with the headline and image 
+ prettier code formatting

### CODE REVIEW

**Comment by jo-svg** [comment]
Screenshot 2025-12-17 at 12 16 45 PM
is this supposed to be empty lmfao

**Comment by katiekhamarkhanova** [comment]
no it is not idk why it is like that

**Comment by katiekhamarkhanova** [comment]
think i didn't push when i worked from home

**Comment by katiekhamarkhanova** [comment]
😢

**Comment by joe-238** [comment]
it still empty did you push it yet lol

**Comment by katiekhamarkhanova** [comment]
oh wait nah my brain ain't working i'm so tired

it is supposed to be empty i think i wanted to have the full makerspace article popup as a separate component but i just ended up putting it in the makerspaceGrid.vue file

**Comment by katiekhamarkhanova** [comment]
deleted the file

**Comment by jo-svg** [comment]
@katiekhamarkhanova REMINDER TO YOU AND ME THAT I ASKED YOU TO MAKE IT A COMPONENT

File: siths-redesign/components/FullArticle.vue [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+  >
+    <div
+      class="flex max-h-[85vh] w-full max-w-3xl flex-col overflow-hidden rounded-xl bg-white text-black shadow-2xl"
+      @click.stop
+    >
+      <div class="border-gray-200 flex items-start justify-between border-b p-6">
+        <h2 class="text-gray-900 pr-4 text-2xl font-bold">{{ article.headline }}</h2>
+        <button
+          @click="$emit('close')"
+          class="text-gray-400 hover:text-gray-600 p-1 transition-colors hover:cursor-pointer"
```
Comment (jo-svg) [inline siths-redesign/components/FullArticle.vue]: Theres no icon or context to this button

File: siths-redesign/components/FullArticle.vue [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+      </div>
+    </div>
+  </div>
+</template>
+
+<script setup>
+defineProps({
+  article: {
+    type: Object,
+    default: null
```
Comment (jo-svg) [inline siths-redesign/components/FullArticle.vue]: Maybe change this ot required: true instead of default null

File: siths-redesign/components/FullArticle.vue [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+        <button
+          @click="$emit('close')"
+          class="text-gray-400 hover:text-gray-600 p-1 transition-colors hover:cursor-pointer"
+        ></button>
+      </div>
+      <div class="flex-1 overflow-y-auto p-6">
+        <img
+          v-if="article.imageUrl"
+          :src="article.imageUrl"
+          :alt="article.headline"
```
Comment (jo-svg) [inline siths-redesign/components/FullArticle.vue]: Could be more descriptive

File: siths-redesign/components/FullArticle.vue [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+    v-if="article"
+    class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 backdrop-blur-sm"
+    @click="$emit('close')"
+  >
+    <div
+      class="flex max-h-[85vh] w-full max-w-3xl flex-col overflow-hidden rounded-xl bg-white text-black shadow-2xl"
+      @click.stop
+    >
+      <div class="border-gray-200 flex items-start justify-between border-b p-6">
+        <h2 class="text-gray-900 pr-4 text-2xl font-bold">{{ article.headline }}</h2>
```
Comment (jo-svg) [inline siths-redesign/components/FullArticle.vue]: Nitpick idk if prettier did this but i think doing pr-4 text-2xl font-bold text-gray-900 is better

File: siths-redesign/components/MakerspaceGrid.vue [hunk 5]
```diff
@@ -23,78 +19,83 @@
...
+      :total-pages="totalPages"
+      @previous="previousPage"
+      @next="nextPage"
+      @go-to="goToPage"
+    />
   </div>
 </template>
 
 <script setup>
+import FullArticle from './FullArticle.vue'
```
Comment (jo-svg) [inline siths-redesign/components/MakerspaceGrid.vue]: Imports while using nuxt?

File: siths-redesign/components/MakerspaceGrid.vue [hunk 6]
```diff
@@ -1,20 +1,16 @@
...
       >
         <div
-          :class="[
-            'flex flex-col overflow-hidden rounded-lg bg-white text-black shadow-lg transition-all duration-300 md:flex-row',
-            article.externalLink ? 'hover:shadow-2xl' : ''
-          ]"
+          class="flex flex-col overflow-hidden rounded-lg bg-white text-black shadow-lg transition-all duration-300 hover:shadow-2xl md:flex-row"
         >
           <div
             v-if="article.imageUrl"
```
Comment (jo-svg) [inline siths-redesign/components/MakerspaceGrid.vue:18]: Feels like unnecessary div, you xan js add this to img

File: siths-redesign/components/MakerspaceGrid.vue [hunk 7]
```diff
@@ -1,20 +1,16 @@
 <template>
   <div class="w-full px-4 lg:w-3/5 xl:w-3/6">
     <div class="flex flex-col gap-6">
-      <div
-        v-for="article in paginatedArticles"
+      <a
+        v-for="article in paginatedArticles.filter((a) => a.externalLink)"
```
Comment (jo-svg) [inline siths-redesign/components/MakerspaceGrid.vue]: Make a variable for this

const externalArticles = computed(() =>
  paginatedArticles.value.filter(a => a.externalLink)
)
const internalArticles = computed(() =>
  paginatedArticles.value.filter(a => !a.externalLink)
)

File: siths-redesign/components/MakerspaceGrid.vue [hunk 8]
```diff
@@ -1,20 +1,16 @@
...
         :key="article._id"
-        :is="article.externalLink ? 'a' : 'div'"
```
Comment (jo-svg) [inline siths-redesign/components/MakerspaceGrid.vue:7]: Y delete this

Comment (jo-svg) [reply siths-redesign/components/MakerspaceGrid.vue:7]: Wouldnt it be better to js run that one part once? Like ion think u need two divs to check if its an internal or external article

File: siths-redesign/components/MakerspaceGrid.vue [hunk 9]
```diff
@@ -105,6 +106,16 @@ const props = defineProps({
     default: 5
   }
 })
+const selectedArticle = ref(null)
+
+function openArticle(article) {
+  selectedArticle.value = article
+}
+
+function truncateText(text, maxLength) {
```
Comment (jo-svg) [inline siths-redesign/components/MakerspaceGrid.vue:79]: I couldve sworn i put this in a folder so u didnt need to rewrite this

File: siths-redesign/components/MakerspaceGrid.vue [hunk 10]
```diff
@@ -1,20 +1,16 @@
 <template>
   <div class="w-full px-4 lg:w-3/5 xl:w-3/6">
```
Comment (jo-svg) [inline siths-redesign/components/MakerspaceGrid.vue]: Xl:w- 3/6 -> 1/2

File: siths-redesign/components/MakerspaceGrid.vue [hunk 11]
```diff
@@ -1,20 +1,16 @@
...
         :key="article._id"
-        :is="article.externalLink ? 'a' : 'div'"
-        :href="article.externalLink || undefined"
-        :target="article.externalLink ? '_blank' : undefined"
-        :rel="article.externalLink ? 'noopener noreferrer' : undefined"
-        :class="article.externalLink ? 'group cursor-pointer' : ''"
+        :href="article.externalLink"
+        target="_blank"
+        rel="noopener noreferrer"
+        class="group cursor-pointer"
```
Comment (jo-svg) [inline siths-redesign/components/MakerspaceGrid.vue]: Cursor-pointer is there for <a> is default in browsers

File: siths-redesign/components/Pagination.vue [hunk 12]
```diff
@@ -0,0 +1,48 @@
+<template>
+  <div v-if="totalPages > 1" class="mt-8 flex w-full items-center justify-center gap-4">
+    <button
+      @click="currentPage > 1 ? $emit('previous') : null"
+      :class="[
+        'btn inline-flex',
+        currentPage === 1 ? 'cursor-not-allowed opacity-50' : 'cursor-pointer'
```
Comment (jo-svg) [inline siths-redesign/components/Pagination.vue]: U can use :disabled for this
If u do use that, inside ur class u can put disabled:opacity-50 disabled:cursor-not-allowed
Also u dont need cursor-pointer bc button alr has cursor-pointer as default

File: siths-redesign/components/Pagination.vue [hunk 13]
```diff
@@ -0,0 +1,48 @@
...
+      ]"
+    >
+      ← Previous
+    </button>
+    <div class="flex gap-2">
+      <button
+        v-for="page in totalPages"
+        :key="page"
```
Comment (jo-svg) [inline siths-redesign/components/Pagination.vue:13]: U can also add :disabled= "currentpage === page" so u dknt emit page that is alr active

**Review by jo-svg — CHANGES_REQUESTED** [review]

**Comment by bridgetf7** [comment]
Girl get some sleep it’s break

**Comment by jo-svg** [comment]
LMFAOO igu imma knock out nowww

File: siths-redesign/components/FullArticle.vue (hunk 4 above)
Comment (kennething) [reply siths-redesign/components/FullArticle.vue]: bros going after the CLASS ORDER nah thats crazy even i dont nitpick that hard :shipit:

File: siths-redesign/components/Pagination.vue [hunk 14]
```diff
@@ -0,0 +1,48 @@
+<template>
+  <div v-if="totalPages > 1" class="mt-8 flex w-full items-center justify-center gap-4">
+    <button
+      @click="currentPage > 1 ? $emit('previous') : null"
+      :class="[
```
Comment (kennething) [inline siths-redesign/components/Pagination.vue]: > \[!CAUTION\]
> vue will keep wasting resources to rerender this string every time `variable` gets changed
> this is what u need to do in react
> **NEVER** do something like react
> if ur doing something like react ur doing it **WRONG**
> react bad

if it doesnt need to change it doesnt need to get v-binded

```rs
class="non changing classes"
:class="boolean ? 'wtv' : 'wtv'"
```

File: siths-redesign/pages/cte/makerspace.vue [hunk 15]
```diff
@@ -1,6 +1,7 @@
 <template>
     <h1 class="mb-4 text-center text-2xl md:text-3xl lg:text-4xl">Career and Technical Education</h1>
     <div class="mb-6 flex flex-col items-start justify-center px-4 md:flex-row">
+        <SubpageMenu :pages="cteLinks" :active="'About'" class="block mb-4 lg:absolute left-8 top-40" />
```
Comment (kennething) [inline siths-redesign/pages/cte/makerspace.vue]: u dont need to v-bind for strings
`active="About"`

File: siths-redesign/components/Pagination.vue (hunk 14 above)
Comment (jo-svg) [reply siths-redesign/components/Pagination.vue]: i was wondering why the days since kenneth reseted 💀

File: siths-redesign/components/MakerspaceGrid.vue (hunk 9 above)
Comment (katiekhamarkhanova) [reply siths-redesign/components/MakerspaceGrid.vue:79]: wait where is it

File: siths-redesign/components/MakerspaceGrid.vue (hunk 11 above)
Comment (katiekhamarkhanova) [reply siths-redesign/components/MakerspaceGrid.vue]: ?

Comment (katiekhamarkhanova) [reply siths-redesign/components/MakerspaceGrid.vue]: nvm

File: siths-redesign/components/MakerspaceGrid.vue (hunk 9 above)
Comment (jo-svg) [reply siths-redesign/components/MakerspaceGrid.vue:79]: maybe im bugging

**Review by jo-svg — APPROVED** [review]
