### PR TITLE
Fix media queries pr2

### LINKED ISSUE #130: fix media queries
fix the following:
- [ ] athletics (subpages)
- [ ] CTE (subpages)

theres def more but uhh fix these for now plox

### PR DESCRIPTION
**Pull request by Abeeha-Z**
new pr for issue #130

### CODE REVIEW

**Comment by jo-svg** [comment]
still didnt fix it btw 😭

File: siths-redesign/pages/athletics/contacts.vue [hunk 1]
```diff
@@ -1,12 +1,8 @@
 <template>
   <h1 class="mb-4 text-center text-2xl md:text-3xl lg:text-4xl">Contacts</h1>
   <div class="flex flex-col items-start justify-center px-4 md:flex-row">
-    <SubpageMenu
-      :pages="subpageLinks"
-      :active="'Contacts'"
-      class="absolute left-8 top-48 mb-4 md:mb-0 md:mr-8"
-    />
-    <div class="flex w-1/2 flex-col items-center justify-center">
+    <SubpageMenu :pages="subpageLinks" :active="'Contacts'" class="left-8 top-48 z-20" />
```
Comment (jo-svg) [inline siths-redesign/pages/athletics/contacts.vue:4]: md + lg

File: siths-redesign/components/SubpageMenu.vue [hunk 2]
```diff
@@ -1,5 +1,5 @@
 <template>
-  <div class="w-full rounded-md p-1 md:w-1/6">
+  <div class="left-8 top-48 z-20 mb-8 w-full rounded-md p-1 md:w-1/6 lg:absolute">
```
Comment (jo-svg) [inline siths-redesign/components/SubpageMenu.vue:2]: i dont think you needed to edit this

Comment (jo-svg) [reply siths-redesign/components/SubpageMenu.vue:2]: or maybe u do

File: siths-redesign/components/contactCard.vue [hunk 3]
```diff
@@ -1,37 +1,40 @@
...
-                    <p>
-                        {{ contact.email }}
-                    </p>
-                </div>
-            </div>
+  <div class="flex w-full flex-col justify-center">
+    <h3>{{ title }}</h3>
+    <div
+      v-for="contact in contacts"
+      class="w-200 relative my-4 ml-0 flex justify-center rounded-lg bg-white/20 p-6"
```
Comment (jo-svg) [inline siths-redesign/components/contactCard.vue]: 200 isnt even a tailwind class, thats basically useless here
also what do you even need ml-0 for

File: siths-redesign/components/contactCard.vue [hunk 4]
```diff
@@ -1,37 +1,40 @@
...
+    >
+      <p class="text-md absolute right-1 top-1 rounded-md bg-black/45 p-1 px-2 text-gold">
+        {{ contact.season.toUpperCase() }}
+      </p>
+      <div class="mt-2 flex flex-wrap items-center md:flex-row">
```
Comment (jo-svg) [inline siths-redesign/components/contactCard.vue]: you dont need md:flex-row, its alr auto set to row if u have flex

File: siths-redesign/components/contactCard.vue [hunk 5]
```diff
@@ -1,37 +1,40 @@
...
+        <div class="p-2">
+          <p class="my-1">{{ contact.sport }}</p>
```
Comment (jo-svg) [inline siths-redesign/components/contactCard.vue]: this isnt a paragraph!! use span instead
same thing w the other ones

File: siths-redesign/pages/athletics/forms.vue [hunk 6]
```diff
@@ -1,13 +1,9 @@
...
   <div class="flex flex-col items-start justify-center px-4 md:flex-row">
-    <SubpageMenu
-      :pages="subpageLinks"
-      :active="'Athletic Forms'"
-      class="absolute left-8 top-48 mb-4 md:mb-0 md:mr-8"
-    />
+    <SubpageMenu :pages="subpageLinks" :active="'Athletic Forms'" />
     <div
-      class="z-20 my-4 flex w-1/2 flex-col items-center justify-center rounded-lg bg-black/40 p-8"
+      class="z-20 mb-10 flex w-full flex-col self-center rounded-lg bg-black/40 p-8 text-center md:mx-10 md:w-1/2"
```
Comment (jo-svg) [inline siths-redesign/pages/athletics/forms.vue]: i think its better to use mx-auto rather than making it 10 because it migth overflow on smaller screens

File: siths-redesign/pages/athletics/contacts.vue (hunk 1 above)
Comment (jo-svg) [reply siths-redesign/pages/athletics/contacts.vue:4]: idk how you check how it looks on diff screens but i use responsive, i want you to chekc all the pages and make sure it doesnt look wonky for when you adjust it because it looks wonky for some (ex: for the dimensions ipad mini for the contacts.vue) 
i am NOT commenting on every single one asking you to fix it

File: siths-redesign/pages/athletics/index.vue [hunk 7]
```diff
@@ -1,16 +1,14 @@
...
-      <h3>McKee - Staten Island Tech Public Schools Athletics League</h3>
-      <p>Home of the Seagulls</p>
+    <SubpageMenu :pages="subpageLinks" :active="'About'" class="left-8 top-48 z-20" />
+    <div class="z-20 flex w-full flex-col text-center md:mx-10 md:w-1/2">
       <!-- psal director message -->
-      <div class="z-20 my-4 w-2/3 rounded-lg bg-black/40 p-8">
+      <h2>McKee - Staten Island Tech Public Schools Athletics League</h2>
+      <p>Home of the Seagulls</p>
+      <div
+        class="z-20 my-4 flex w-full flex-col items-center justify-center rounded-lg bg-black/40 p-8"
```
Comment (jo-svg) [inline siths-redesign/pages/athletics/index.vue:10]: z-index only works if you set the element's position (relative, absolute, fixed, sticky)

File: siths-redesign/pages/cte/index.vue [hunk 8]
```diff
@@ -1,60 +1,79 @@
...
+              gyroscope;
+              picture-in-picture;
+              web-share;
+            "
+            referrerpolicy="strict-origin-when-cross-origin"
+            allowfullscreen
+          ></iframe>
+        </div>
+        <h2 class="py-4 text-xl md:text-2xl">Work-Based Learning</h2>
+        <p class="mb-4 text-sm md:text-base">
```
Comment (jo-svg) [inline siths-redesign/pages/cte/index.vue]: I think you should put all the paragraophs in a parent div and put all teh styling + spacing. its more clean and you dont need to copy n paste shi
ex:
```
<div class="text-sm md:text-base space-y-4">
  <p>hihi</p>
  <p>lalalala</p>
  <p>so cool wowie</p>
</div>
```

Comment (jo-svg) [reply siths-redesign/pages/cte/index.vue]: do the same for others lowk

**Review by jo-svg — CHANGES_REQUESTED** [review]

File: siths-redesign/pages/athletics/contacts.vue (hunk 1 above)
Comment (jo-svg) [reply siths-redesign/pages/athletics/contacts.vue:4]: image
this is legit how it looks like on an ipad mini btw

File: siths-redesign/pages/athletics/index.vue (hunk 7 above)
Comment (jo-svg) [reply siths-redesign/pages/athletics/index.vue:10]: uhh u didnt fix this

**Review by jo-svg — APPROVED** [review]
